- name: es相关文件夹创建授权
  file:
    path: "{{ item }}"
    owner: elasticsearch
    group: elasticsearch
    state: directory
    recurse: yes
  vars:
    item:
    - /data/ela-data
    - /data/ela-log


- name: 备份elasticsearch.yml.bak文件
  shell: mv /etc/elasticsearch/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml.bak
    

- name: 配置elasticsearch.yml文件
  blockinfile:
     path: /etc/my.cnf
      block: |
        cluster.name: elk-cluster
        node.master: true
        node.data: true
        node.name: elk01
        path.data: /data/ela-data
        path.logs: /data/ela-log
        network.host: "{{ ansible_ssh_host }}"
        http.port: 9200
        discovery.seed_hosts: ["\"{{ ansible_ssh_host }}\"", "ip1", "ip2"]
        cluster.initial_master_nodes: ["\"{{ ansible_ssh_host }}\"", "ip1", "ip2"]
        http.cors.enabled: true
        http.cors.allow-origin: "*"



- name: 优化jvm堆内存容量
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: '1g'
    line: '400m'
    state: present
    

